#!/bin/bash
# Copyright (c) 2013 Roman Rader. All rights reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e

[ -z "$1" ] && USER=root || USER="$1"

id=0
declare -A MACHINE

while read machine; do
    id=$((id+1))
    uuid=$(echo $machine | sed -r 's/.*(\{.*\}).*/\1/g')
    MACHINE[${id}_uuid]="$uuid"
    hostport=$(VBoxManage showvminfo $uuid | grep "guest port = 22" | sed -r 's/.*host port = ([0-9]+).*/\1/g')
    MACHINE[${id}_port]="$hostport"
    echo " $id) ${machine} <${hostport}>"
done < <(VBoxManage list runningvms)

echo -n "select> "
read num

if (( num > ${#MACHINE[@]} )); then
    echo "Invalid index"
    exit 1
fi

ssh -p ${MACHINE[${num}_port]} $USER@localhost
